"""Visualize callable models and classify them by heuristic strength tiers.

Usage:
    python plot_model_strength.py
    python plot_model_strength.py --csv available_llms_20260419_112300.csv
    python plot_model_strength.py --csv available_llms_20260419_112300.csv --out-dir .

Notes:
    - This is a rule-based heuristic classifier, not a benchmark leaderboard.
    - It is designed for fast visualization from model ID strings.
"""

from __future__ import annotations

import argparse
import csv
import math
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt


TIER_ORDER = ["S", "A", "B", "C"]
TIER_COLORS = {
    "S": "#1d4ed8",
    "A": "#16a34a",
    "B": "#f59e0b",
    "C": "#dc2626",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Classify callable models by strength tier and draw a visualization."
    )
    parser.add_argument(
        "--csv",
        default="available_llms_20260419_112300.csv",
        help="Input CSV path generated by list_available_llms.py",
    )
    parser.add_argument(
        "--out-dir",
        default=".",
        help="Output directory for figure and classified CSV",
    )
    parser.add_argument(
        "--top-families",
        type=int,
        default=12,
        help="How many model families to show in the family chart",
    )
    return parser.parse_args()


def extract_size_b(model_id: str) -> float:
    # Match patterns such as 7b, 72b, 1.5b, 235b-a22b.
    matches = re.findall(r"(\d+(?:\.\d+)?)b", model_id.lower())
    if not matches:
        return 0.0
    # Use the largest number found as a coarse model-size proxy.
    return max(float(x) for x in matches)


def get_family(model_id: str) -> str:
    low = model_id.lower()
    if "/" in low:
        return low.split("/", 1)[0]

    match = re.match(r"([a-z]+)", low)
    return match.group(1) if match else "other"


def score_model(model_id: str) -> float:
    low = model_id.lower()
    score = 50.0

    size_b = extract_size_b(low)
    if size_b > 0:
        score += min(35.0, size_b * 0.35)

    positive_keywords = {
        "max": 14,
        "plus": 10,
        "pro": 9,
        "thinking": 12,
        "deep-research": 12,
        "deep-search": 9,
        "r1": 10,
        "next": 6,
        "omni": 4,
        "instruct": 2,
    }
    negative_keywords = {
        "flash": -12,
        "turbo": -8,
        "lite": -10,
        "mini": -10,
        "distill": -18,
        "preview": -5,
        "realtime": -8,
    }

    modality_penalty_keywords = [
        "tts",
        "asr",
        "speech",
        "image",
        "ocr",
        "mt",
        "livetranslate",
        "s2s",
        "vc",
        "vd",
    ]

    for keyword, delta in positive_keywords.items():
        if keyword in low:
            score += delta

    for keyword, delta in negative_keywords.items():
        if keyword in low:
            score += delta

    if any(keyword in low for keyword in modality_penalty_keywords):
        score -= 12

    return max(0.0, min(100.0, score))


def score_to_tier(score: float) -> str:
    if score >= 78:
        return "S"
    if score >= 62:
        return "A"
    if score >= 45:
        return "B"
    return "C"


def load_models(csv_path: Path) -> List[Dict[str, str]]:
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    return rows


def classify(rows: List[Dict[str, str]]) -> List[Dict[str, str]]:
    out: List[Dict[str, str]] = []
    for row in rows:
        model_id = str(row.get("id", "")).strip()
        if not model_id:
            continue

        family = get_family(model_id)
        score = score_model(model_id)
        tier = score_to_tier(score)

        out.append(
            {
                "id": model_id,
                "family": family,
                "strength_score": f"{score:.1f}",
                "strength_tier": tier,
                "owned_by": str(row.get("owned_by", "")),
                "created": str(row.get("created", "")),
            }
        )

    out.sort(key=lambda x: (TIER_ORDER.index(x["strength_tier"]), -float(x["strength_score"]), x["id"]))
    return out


def save_classified_csv(rows: List[Dict[str, str]], out_path: Path) -> None:
    headers = ["id", "family", "strength_score", "strength_tier", "owned_by", "created"]
    with out_path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(rows)


def build_family_tier_counts(rows: List[Dict[str, str]], top_families: int) -> Tuple[List[str], Dict[str, List[int]]]:
    family_counts = Counter(row["family"] for row in rows)
    most_common = [name for name, _ in family_counts.most_common(max(1, top_families))]

    families = list(most_common)
    if len(family_counts) > len(most_common):
        families.append("other")

    matrix: Dict[str, List[int]] = {tier: [0] * len(families) for tier in TIER_ORDER}

    family_index = {name: i for i, name in enumerate(families)}
    for row in rows:
        fam = row["family"]
        idx = family_index.get(fam, family_index.get("other", 0))
        matrix[row["strength_tier"]][idx] += 1

    return families, matrix


def plot_visual(rows: List[Dict[str, str]], out_png: Path, top_families: int) -> None:
    tier_counts = Counter(row["strength_tier"] for row in rows)
    counts = [tier_counts.get(t, 0) for t in TIER_ORDER]

    families, family_matrix = build_family_tier_counts(rows, top_families)

    plt.style.use("seaborn-v0_8-whitegrid")
    fig, (ax1, ax2) = plt.subplots(
        2,
        1,
        figsize=(13, 10),
        gridspec_kw={"height_ratios": [1, 1.8]},
    )

    total = max(1, sum(counts))
    wedges, _, autotexts = ax1.pie(
        counts,
        labels=TIER_ORDER,
        colors=[TIER_COLORS[t] for t in TIER_ORDER],
        autopct=lambda p: f"{p:.1f}%\n({int(round(total * p / 100.0))})",
        startangle=110,
        wedgeprops={"linewidth": 1, "edgecolor": "white"},
        textprops={"fontsize": 10},
    )
    for t in autotexts:
        t.set_color("white")
        t.set_fontsize(9)

    centre = plt.Circle((0, 0), 0.58, fc="white")
    ax1.add_artist(centre)
    ax1.text(0, 0, f"Total\n{total}", ha="center", va="center", fontsize=12, fontweight="bold")
    ax1.set_title("Callable Models Strength Tier Distribution", fontsize=14, fontweight="bold")

    y = list(range(len(families)))
    left = [0] * len(families)
    for tier in TIER_ORDER:
        values = family_matrix[tier]
        ax2.barh(y, values, left=left, label=f"Tier {tier}", color=TIER_COLORS[tier], alpha=0.9)
        left = [left[i] + values[i] for i in range(len(values))]

    ax2.set_yticks(y)
    ax2.set_yticklabels(families)
    ax2.invert_yaxis()
    ax2.set_xlabel("Model Count")
    ax2.set_title("Model Families by Strength Tier (Stacked)", fontsize=13, fontweight="bold")
    ax2.legend(loc="lower right")

    # Put total count labels at the end of each stacked bar.
    totals = [sum(family_matrix[t][i] for t in TIER_ORDER) for i in range(len(families))]
    for i, t in enumerate(totals):
        if t > 0:
            ax2.text(t + 0.3, i, str(t), va="center", fontsize=9)

    fig.tight_layout()
    fig.savefig(out_png, dpi=280)
    plt.close(fig)


def main() -> None:
    args = parse_args()

    csv_path = Path(args.csv).resolve()
    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    rows = load_models(csv_path)
    classified = classify(rows)
    if not classified:
        raise RuntimeError("No models found in CSV.")

    base_name = csv_path.stem
    classified_csv = out_dir / f"{base_name}_classified_strength.csv"
    out_png = out_dir / f"{base_name}_strength_visualization.png"

    save_classified_csv(classified, classified_csv)
    plot_visual(classified, out_png, top_families=max(3, args.top_families))

    tier_counts = Counter(row["strength_tier"] for row in classified)
    print("Heuristic classification complete.")
    print(f"Input CSV: {csv_path}")
    print(f"Output figure: {out_png}")
    print(f"Output classified CSV: {classified_csv}")
    print("Tier counts:")
    for tier in TIER_ORDER:
        print(f"  {tier}: {tier_counts.get(tier, 0)}")


if __name__ == "__main__":
    main()
